//Immediately Invoked Function Expressions (IIFI)

(function first(){
    //Named IIFI
    console.log("I'm First");
 })(); //semicolon is very important here 

((name) => {
    //normal IIFI
    console.log(name);
 })("Sage");


 //()() the first parenthesis is the definatio of fuxn, the second parenthesis is for the calling for the fuxn
 //We use IIFI for removing the pollution generated by the global pollution
 //IIFI is the very first fuxn which will execute